let questions = [{
    questionText: "How many different colors of pockets are on a roulette wheel?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: true,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "1",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "2",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "3",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "4",
        answerImg: "",
        isCorrect: true,
      },
    ],
  },
  {
    questionText: "Which card game is usually played by only one person?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: true,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "Solitude",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Solitaire",
        answerImg: "",
        isCorrect: true,
      },
      {
        answerText: "Poker",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Uno",
        answerImg: "",
        isCorrect: true,
      },
    ],
  },
  {
    questionText: "Which one of the following is NOT a flavor of M&M candy?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: true,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "Peanut",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Dark chocolate",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Milk chocolate",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Brussel sprout",
        answerImg: "",
        isCorrect: true,
      },
    ],
  },
  {
    questionText: "Which of these birds is extinct?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: true,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "Emu",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Moa",
        answerImg: "",
        isCorrect: true,
      },
      {
        answerText: "Kiwi",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Ostrich",
        answerImg: "",
        isCorrect: false,
      },
    ],
  },
  {
    questionText: "Which bird species is now extinct from mainland New Zealand?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: true,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "Kakapo",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Wood pigeon",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Hihi",
        answerImg: "",
        isCorrect: true,
      },
      {
        answerText: "Kiwi",
        answerImg: "",
        isCorrect: false,
      },
    ],
  },
  {
    questionText: "Which of the following foods is not traditionally cooked by baking it?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: true,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "Spaghetti",
        answerImg: "",
        isCorrect: true,
      },
      {
        answerText: "Cookies",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Apple pie",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Lasagna",
        answerImg: "",
        isCorrect: false,
      },
    ],
  },
  {
    questionText: "Which of these is NOT a golf brand?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: true,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "Titleist",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Sunningdale",
        answerImg: "",
        isCorrect: true,
      },
      {
        answerText: "PING",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Callaway",
        answerImg: "",
        isCorrect: false,
      },
    ],
  },
  {
    questionText: "What does a normal human body NOT have exactly two of?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: true,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "Eyes",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Kidneys",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Brains",
        answerImg: "",
        isCorrect: true,
      },
      {
        answerText: "Lungs",
        answerImg: "",
        isCorrect: false,
      },
    ],
  },
  {
    questionText: "Which of the following is NOT a measurement of distance?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: true,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "Hour",
        answerImg: "",
        isCorrect: true,
      },
      {
        answerText: "Centimeter",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Kilometer",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Meter",
        answerImg: "",
        isCorrect: false,
      },
    ],
  },
  {
    questionText: "Which human organ can be affected by an astrocytoma tumor?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: true,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "Heart",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Smalll intestine",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Kidney",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Brain",
        answerImg: "",
        isCorrect: true,
      },
    ],
  },
  {
    questionText: "'Creme de Abacate' is a brazilian dessert made from which green fruit?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: true,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "Avocado",
        answerImg: "",
        isCorrect: true,
      },
      {
        answerText: "Lime",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Grape",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Kiwi",
        answerImg: "",
        isCorrect: false,
      },
    ],
  },
  {
    questionText: "How many London Underground stations were there in 2007?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: true,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "38",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "275",
        answerImg: "",
        isCorrect: true,
      },
      {
        answerText: "169",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "400",
        answerImg: "",
        isCorrect: false,
      },
    ],
  },
  {
    questionText: "Which one of the following is NOT the name of a space telescope?",
    questionType: "medium",
    questionImg: "",
    isMultipleChoice: true,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "Kepler",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "The Millennium Falcon",
        answerImg: "",
        isCorrect: true,
      },
      {
        answerText: "Hubble",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Astrosat",
        answerImg: "",
        isCorrect: false,
      },
    ],
  },
  {
    questionText: "Which of these fruits do NOT grow on vines?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: true,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "Tomatoes",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Cucumbers",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Kiwis",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Oranges",
        answerImg: "",
        isCorrect: true,
      },
    ],
  },
  {
    questionText: "Which of the following animals does NOT lay eggs?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: true,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "Pigs",
        answerImg: "",
        isCorrect: true,
      },
      {
        answerText: "Fish",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Birds",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Frogs",
        answerImg: "",
        isCorrect: false,
      },
    ],
  },
  {
    questionText: "Which of these is a city?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: true,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "Tuvalu",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Sri Lanka",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Ankara",
        answerImg: "",
        isCorrect: true,
      },
      {
        answerText: "Lesotho",
        answerImg: "",
        isCorrect: false,
      },
    ],
  },
  {
    questionText: "Which one of the following stars was NOT a child actor?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: true,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "Macaulay Culkin",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Jack Nicholson",
        answerImg: "",
        isCorrect: true,
      },
      {
        answerText: "Shirley Temple",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Drew Barrymore",
        answerImg: "",
        isCorrect: false,
      },
    ],
  },
  {
    questionText: "Which word refers to molten rock below the earth's surface?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: true,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "Cinder",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Granite",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Lava",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Magma",
        answerImg: "",
        isCorrect: true,
      },
    ],
  },
  {
    questionText: "What kind of creature is Shrek, in the movie of a same name?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: true,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "A dwarf",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "A monster",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "An ogre",
        answerImg: "",
        isCorrect: true,
      },
      {
        answerText: "A donkey",
        answerImg: "",
        isCorrect: false,
      },
    ],
  },
  {
    questionText: "Who irritated the British by cutting down a flagpole in New Zealand, 1845?",
    questionType: "medium",
    questionImg: "",
    isMultipleChoice: true,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "Hōne Heke",
        answerImg: "",
        isCorrect: true,
      },
      {
        answerText: "Michael Collins",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Che Guevara",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Boudica",
        answerImg: "",
        isCorrect: false,
      },
    ],
  },
  {
    questionText: "The Latvian flag, which is red-white-red, is often mistaken for the flag of which European country?",
    questionType: "medium",
    questionImg: "",
    isMultipleChoice: true,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "Malta",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Poland",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Austria",
        answerImg: "",
        isCorrect: true,
      },
      {
        answerText: "Belarus",
        answerImg: "",
        isCorrect: false,
      },
    ],
  },
  {
    questionText: "Which animal cannot move backwards?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: true,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "Shark",
        answerImg: "",
        isCorrect: true,
      },
      {
        answerText: "Bird",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Dog",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Lion",
        answerImg: "",
        isCorrect: false,
      },
    ],
  },
  {
    questionText: "Which animal is NOT native to Australia?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: true,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "Koala",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Dingo",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Kangaroo",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Mustang",
        answerImg: "",
        isCorrect: true,
      },
    ],
  },
  {
    questionText: "What device would you use to open and close a circuit?",
    questionType: "medium",
    questionImg: "",
    isMultipleChoice: true,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "Nail",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Paddle",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Switch",
        answerImg: "",
        isCorrect: true,
      },
      {
        answerText: "Press",
        answerImg: "",
        isCorrect: false,
      },
    ],
  },
  {
    questionText: "Which one of the following plants is a type of edible thistle?",
    questionType: "medium",
    questionImg: "",
    isMultipleChoice: true,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "Artichoke",
        answerImg: "",
        isCorrect: true,
      },
      {
        answerText: "Honeysuckle",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Cabbage",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Dandelion",
        answerImg: "",
        isCorrect: false,
      },
    ],
  },
  {
    questionText: "Which of these units of digital information is the largest?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: true,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "Kilobyte",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Yottabyte",
        answerImg: "",
        isCorrect: true,
      },
      {
        answerText: "Terrabyte",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Gigabyte",
        answerImg: "",
        isCorrect: false,
      },
    ],
  },
  {
    questionText: "Which of the following is a genre of literature that focuses on the growth of a protagonist from youth to adulthood?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: true,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "Growing-even-older",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "No-longer-young",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Coming-of-age",
        answerImg: "",
        isCorrect: true,
      },
      {
        answerText: "Becoming-very-old",
        answerImg: "",
        isCorrect: false,
      },
    ],
  },
  {
    questionText: "Which of the following is a children's novel by Roald Dahl?",
    questionType: "medium",
    questionImg: "",
    isMultipleChoice: true,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "Cool Mr Cat",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Awesome Mr Alpaca",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Brilliant Mr Bear",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Fantastic Mr Fox",
        answerImg: "",
        isCorrect: true,
      },
    ],
  },
  {
    questionText: "What side of the body does the human heart typically tilt towards?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: true,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "The bottom",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "The right",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "The back",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "The left",
        answerImg: "",
        isCorrect: true,
      },
    ],
  },
  {
    questionText: "'Home and Away' is set in which fictional seaside town?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: true,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "Summer Bay",
        answerImg: "",
        isCorrect: true,
      },
      {
        answerText: "Erinsborough",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Weatherfield",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Quahog",
        answerImg: "",
        isCorrect: false,
      },
    ],
  },
  {
    questionText: "Which of the following is NOT generally considered one of the national dishes of Great Britain?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: true,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "Fish and chips",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Chicken tikka masala",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Hot dogs",
        answerImg: "",
        isCorrect: true,
      },
      {
        answerText: "Roast dinner",
        answerImg: "",
        isCorrect: false,
      },
    ],
  },
  {
    questionText: "Which one of the following colors are cucumbers commonly found in?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: true,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "Black",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Pink",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Green",
        answerImg: "",
        isCorrect: true,
      },
      {
        answerText: "Purple",
        answerImg: "",
        isCorrect: false,
      },
    ],
  },
  {
    questionText: "Which form of transportation was invented first?",
    questionType: "medium",
    questionImg: "",
    isMultipleChoice: true,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "The train",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "The boat",
        answerImg: "",
        isCorrect: true,
      },
      {
        answerText: "The airplane",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "The automobile",
        answerImg: "",
        isCorrect: false,
      },
    ],
  },
  {
    questionText: "Which plant species does the plum belong to?",
    questionType: "medium",
    questionImg: "",
    isMultipleChoice: true,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "Citrus",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Stone fruits",
        answerImg: "",
        isCorrect: true,
      },
      {
        answerText: "Pome",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Nut",
        answerImg: "",
        isCorrect: false,
      },
    ],
  },
  {
    questionText: "What gas glows orange when electricity is passed through it?",
    questionType: "medium",
    questionImg: "",
    isMultipleChoice: true,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "Oxygen",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Hydrogen",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Neon",
        answerImg: "",
        isCorrect: true,
      },
      {
        answerText: "Chlorine",
        answerImg: "",
        isCorrect: false,
      },
    ],
  },
  {
    questionText: "Which country has Nuku'alofa as its capital?",
    questionType: "medium",
    questionImg: "",
    isMultipleChoice: true,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "Tonga",
        answerImg: "",
        isCorrect: true,
      },
      {
        answerText: "Algeria",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Peru",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Oman",
        answerImg: "",
        isCorrect: false,
      },
    ],
  },
  {
    questionText: "Which of these is a British clothing brand that is sold worldwide?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: true,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "Chair",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Stool",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Seat",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Bench",
        answerImg: "",
        isCorrect: true,
      },
    ],
  },
  {
    questionText: "Which of the figures below come next in the sequence of figures shown above?",
    questionType: "hard",
    questionImg: "./q1.png",
    isMultipleChoice: true,
    isVocalQuestion: false,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "",
        answerImg: "./q1-answer-a.png",
        isCorrect: false,
      },
      {
        answerText: "",
        answerImg: "./q1-answer-b.png",
        isCorrect: false,
      },
      {
        answerText: "",
        answerImg: "./q1-answer-c.png",
        isCorrect: false,
      },
      {
        answerText: "",
        answerImg: "./q1-answer-d.png",
        isCorrect: true,
      },
    ],
  },
  {
    questionText: "Which of the figures below comes next in the sequence of figures shown above?",
    questionType: "hard",
    questionImg: "./q2.png",
    isMultipleChoice: true,
    isVocalQuestion: false,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "",
        answerImg: "./q2-answer-a.png",
        isCorrect: false,
      },
      {
        answerText: "",
        answerImg: "./q2-answer-b.png",
        isCorrect: false,
      },
      {
        answerText: "",
        answerImg: "./q2-answer-c.png",
        isCorrect: true,
      },
      {
        answerText: "",
        answerImg: "./q2-answer-d.png",
        isCorrect: false,
      },
    ],
  },
  {
    questionText: "Which of the figures below come next in the sequence of figures shown above?",
    questionType: "hard",
    questionImg: "./q3.png",
    isMultipleChoice: true,
    isVocalQuestion: false,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "",
        answerImg: "./q3-answer-a.png",
        isCorrect: false,
      },
      {
        answerText: "",
        answerImg: "./q3-answer-b.png",
        isCorrect: true,
      },
      {
        answerText: "",
        answerImg: "./q3-answer-c.png",
        isCorrect: false,
      },
      {
        answerText: "",
        answerImg: "./q3-answer-d.png",
        isCorrect: false,
      },
    ],
  },
  {
    questionText: "Thirsty is to drink as exhausted is to ___ ?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: true,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "Sweat",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Walk",
        answerImg: "",
        isCorrect: true,
      },
      {
        answerText: "Tire",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Rest",
        answerImg: "",
        isCorrect: false,
      },
    ],
  },
  {
    questionText: "Which of the following is the opposite of the word 'biased'?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: true,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "Reasonable",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Objective",
        answerImg: "",
        isCorrect: true,
      },
      {
        answerText: "Unfair",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Partial",
        answerImg: "",
        isCorrect: false,
      },
    ],
  },
  {
    questionText: "Assumptions:\nProduct A costs twice as much as Product C.\nProduct C costs less than Product D and the same as Product B.\n\nConclusion:\nProduct D costs half as much as Product A.\nIf the assumptions are true, is the conclusion:",
    questionType: "hard",
    questionImg: "",
    isMultipleChoice: true,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "Incorrect",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Cannot be determined based on the information available",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Correct",
        answerImg: "",
        isCorrect: true,
      },
    ],
  },
  {
    questionText: "Which number has the lowest value?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: true,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "0.20 + 0.31",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "1/4 + 1/4",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "0.10 + 1/2",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "0.35 + 0.12",
        answerImg: "",
        isCorrect: true,
      },
    ],
  },
  {
    questionText: "Which of the following is the opposite of 'severe'?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: true,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "Difficult",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Gentle",
        answerImg: "",
        isCorrect: true,
      },
      {
        answerText: "Tolerant",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Patient",
        answerImg: "",
        isCorrect: false,
      },
    ],
  },
  {
    questionText: "What is the next number in the sequence below?\n3    9    21    45",
    questionType: "medium",
    questionImg: "",
    isMultipleChoice: true,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "78",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "69",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "93",
        answerImg: "",
        isCorrect: true,
      },
      {
        answerText: "66",
        answerImg: "",
        isCorrect: false,
      },
    ],
  },
  {
    questionText: "Agenda is to meeting as itinerary is to ___ ?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: true,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "Direction",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Trip",
        answerImg: "",
        isCorrect: true,
      },
      {
        answerText: "Route",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Schedule",
        answerImg: "",
        isCorrect: false,
      },
    ],
  },
  {
    questionText: 'Which one of the following was NOT a standard game piece in the original version of the board game "Monopoly"?',
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: true,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "Dumpster",
        answerImg: "",
        isCorrect: true,
      },
      {
        answerText: "Race car",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Battleship",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Top hat",
        answerImg: "",
        isCorrect: false,
      },
    ],
  },
  {
    questionText: "Which of these was NOT one of the original classes in the fantasy game World of Warcraft?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: true,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "Trolls",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Dwarves",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Bomb disposal experts",
        answerImg: "",
        isCorrect: true,
      },
      {
        answerText: "Orcs",
        answerImg: "",
        isCorrect: false,
      },
    ],
  },
  {
    questionText: "Who is believed to have created the first jigsaw puzzle?",
    questionType: "medium",
    questionImg: "",
    isMultipleChoice: true,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "John F. Kennedy",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "John Legend",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "John Lennon",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "John Spilsbury",
        answerImg: "",
        isCorrect: true,
      },
    ],
  },
  {
    questionText: "What is the capital city of Cuba?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: true,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "Rome",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Manila",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Seoul",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Havana",
        answerImg: "",
        isCorrect: true,
      },
    ],
  },
  {
    questionText: "Dracula is a horror story about what kind of creature?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: true,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "A Ghost",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "A Werewolf",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "A Vampire",
        answerImg: "",
        isCorrect: true,
      },
      {
        answerText: "A Zombie",
        answerImg: "",
        isCorrect: false,
      },
    ],
  },
  {
    questionText: 'Who provides the voice of Aslan in the 2008 film "Prince Caspian"?',
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: true,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "George Clooney",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Liam Neeson",
        answerImg: "",
        isCorrect: true,
      },
      {
        answerText: "Brad Pitt",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Jim Carrey",
        answerImg: "",
        isCorrect: false,
      },
    ],
  },
  {
    questionText: "Which of the following is NOT a chemical symbol on the Periodic Table?",
    questionType: "medium",
    questionImg: "",
    isMultipleChoice: true,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "P",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Mn",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Gh",
        answerImg: "",
        isCorrect: true,
      },
      {
        answerText: "Cs",
        answerImg: "",
        isCorrect: false,
      },
    ],
  },
  {
    questionText: "Who was the ruler of England from 1837-1901?",
    questionType: "medium",
    questionImg: "",
    isMultipleChoice: true,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "King Abdullah II",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Emperor Pedro I",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Queen Victoria",
        answerImg: "",
        isCorrect: true,
      },
      {
        answerText: "King Abdulaziz",
        answerImg: "",
        isCorrect: false,
      },
    ],
  },
  {
    questionText: "What industry did American businessman J. P. Morgan mainly work in?",
    questionType: "medium",
    questionImg: "",
    isMultipleChoice: true,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "Finance",
        answerImg: "",
        isCorrect: true,
      },
      {
        answerText: "Steel",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Oil",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Railways",
        answerImg: "",
        isCorrect: false,
      },
    ],
  },
  {
    questionText: "Which baseball player's signature is on the Converse All Star sneaker logo?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: true,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [{
        answerText: "Michael Jordan",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "David Beckham",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Tiger Woods",
        answerImg: "",
        isCorrect: false,
      },
      {
        answerText: "Chuck Taylor",
        answerImg: "",
        isCorrect: true,
      },
    ],
  },
  {
    questionText: "What's 2 + 18 equal to?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "Say the word 'cinnamon'",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "Say the word 'Anemone'",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "Say the first word that comes to mind about 'pedophile'",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "Say the first word that comes to mind about 'tree burst'",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "Say the first word that comes to mind about 'exoskeleton'",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "Say the first word that comes to mind about 'extremist'",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "Say the first word that comes to mind about 'sister'",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "In one sentence, explain the difference between gender, sex, and sexuality.",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "Out of the list of following people, indicate by checking the corresponding box yes or no for each whether the named individual is someone with whom you have had an intimate relationship in the last 5 years.",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: false,
    isForcedAnswer: true,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [
      "Sally",
      "Susanne",
      "Angelica",
      "Alberto",
      "Ruth",
      "Alex",
      "Lafayette",
    ],
  },
  {
    questionText: "Indicate which of the following States are located south of Virginia in the United States by checking the corresponding box, yes or no, for each of the following:",
    questionType: "medium",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: false,
    isForcedAnswer: true,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [
      "Missouri",
      "Mississippi",
      "Kentucky",
      "Florida",
      "Indiana",
      "Lousiana",
    ],
  },
  {
    questionText: "Indicate which of the following are indictable offenses in Queensland by checking the corresponsing box, yer or no, for each of the following:",
    questionType: "medium",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: false,
    isForcedAnswer: true,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [
      "Forgery",
      "Assault",
      "Indecent exposure",
      "Murder",
      "Homicide",
      "Suicide",
    ],
  },
  {
    questionText: "Indicate which words are a synonym for anger by checking the corresponding box, yes or no, for each of the following:",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: false,
    isForcedAnswer: true,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [
      "Fury",
      "Vengeful",
      "Rage",
      "Merciless",
      "Irritation",
      "Unforgiving",
    ],
  },
  {
    questionText: "Indicate which subjects have been covered so far in this test by checking the corresponding box, yes or no, for each of the following:",
    questionType: "medium",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: false,
    isForcedAnswer: true,
    isShortAnswer: false,
    isDrawingQuestion: false,
    hasBeenAsked: false,
    answers: [
      "North America",
      "North America State",
      "The United States of America",
      "States that were part of the American Confederacy",
      "North American State borders",
      "North American Cartography",
      "American Topography",
      "American Geography",
    ],
  },
  {
    questionText: "Islamic Extremism is to Islam as ____ is to Christianity",
    questionType: "medium",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What is an argument that is logically unsound called?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What is the maiden name of your mother-in-law?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "You are inside a burning building and you need to put the fire out.\nWhat is the first thing you should do?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "You are driving to a time-sensitive meeting that will reward you with $100,000, but on the way, you collide with someone's pet dog.\nThe dog is alive, and there is a vetenarian nearby that could save its life, but doing so will cause you to forfeit the cash reward.\nWhat do you do?",
    questionType: "hard",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "Draw a picture representing someone who was born in the subcontinent",
    questionType: "medium",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: false,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: true,
    hasBeenAsked: false,
  },
  {
    questionText: "Draw a picture representing the meaning of the word 'vestigial'",
    questionType: "medium",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: false,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: true,
    hasBeenAsked: false,
  },
  {
    questionText: "Sketch a symbol that most accurately reflects your political ideological alignment",
    questionType: "medium",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: false,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: true,
    hasBeenAsked: false,
  },
  {
    questionText: "Sketch in as much detail and with as much accuracy as possible to location and scale as you can the room you were in prior to starting this test",
    questionType: "medium",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: false,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: true,
    hasBeenAsked: false,
  },
  {
    questionText: "Create a maze with two possible solutions",
    questionType: "hard",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: false,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: true,
    hasBeenAsked: false,
  },
  {
    questionText: "Draw a machine that could be used to lift a heavy object",
    questionType: "medium",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: false,
    isForcedAnswer: false,
    isShortAnswer: false,
    isDrawingQuestion: true,
    hasBeenAsked: false,
  },
  {
    questionText: "How do you think your exes would describe you?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What’s the most embarrassing thing about your family?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What’s a habit you’ve tried to break and failed?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "If you could only date people of a certain age for the rest of your life, what age would they be?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What is your most irrational fear?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "In what way are you different of your friends?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "If you could have any job in the world, regardless of pay, what would it be?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What’s something that still makes you nervous, no matter how many times you do it?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What’s the most romantic thing you’ve ever done?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "When was a time your body did something embarrassing at the worst possible moment?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "If you could change one thing on a global scale, what would it be?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "Who was your childhood hero?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What conversation did you put off having for a long time?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "If you could live forever at a certain age, what age would you choose?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What is your favourite physical feature about yourself?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "If someone were to take a critical look at your group of friends, how would they describe it?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What event in your life do you feel has shaped you the most significantly?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What are you most particular about in your living space?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What do you think is the scariest aspect of dying?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "How does your personality change when you’re at work?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "In what way do you aspire to be like your mother or father?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What’s the nearest to death experience you’ve ever had?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What was your first impression of the person to your left?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What’s something you kind of wish someone would walk in on you doing?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "If you could replace one aspect of modern life with something from another era, what would it be?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What part of your personality could you call a family trait?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What do you think the person to your left is afraid of?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What is a prejudice that you hold, even though you know you shouldn’t?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "In what way do you not want to be like your parents?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What’s the story of the first time you drank alcohol/got drunk?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What tradition would you like to incorporate into your life?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What was the first thing you ever stole?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What do you want to be your legacy?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What is the worst gift you’ve ever received?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What do you feel is a contradiction in your personality?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What’s something that people usually prefer to do with others, but you prefer to do alone?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "When was the last time you felt an instant connection to someone you’d just met?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What mistake do you keep making again and again?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What’s one skill you wish you had?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "When have you felt the loneliest?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What’s something that would have caused you to end a relationship earlier than you did, if you had been totally honest with yourself?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What have you developed a reputation for that you think is inaccurate?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What aspect of your life currently feels stagnant?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "When in your life have you worked the hardest?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What negative pattern in your life are you consciously or unconsciously choosing to accept?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What is the most significant difference between the person you are now and the person were five years ago?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What parts of your life do you plan most deliberately?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "Would you rather date someone who is inappropriately old or inappropriately young?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What’s the most dishonest or irresponsible thing you’ve ever done at work?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "Of the many roles you play in your life (e.g. coworker, lover, sibling),which do you feel you’re the worst at?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What’s a deal-breaker for you on a first date?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "If you couldn’t live where you live now, where would you move?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What’s one thing you think you’ll always regret?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What’s one thing that you’re looking forward to and one thing that you’re dreading about getting older?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What is your superpower?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What’s a lie you’ve been caught in?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What was your last small act of rebellion?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What accomplishment are you most proud of?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "Which person in your extended family would you least want to spend an hour alone with?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What type of things do you lie about most regularly?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What accents do you find particularly attractive or unattractive?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What’s something that you’ve learned to love?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "How would you describe the person to your right in five words or less?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What’s the stupidest thing you’ve done when drunk?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What did your 13-year-old self think you’d be doing at the age you are now?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What’s something you wish more people understood about you?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What is the best compliment you’ve ever received?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What is the most dramatic way a relationship you’ve been in has ended?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What’s the most public place you’ve ever been naked?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What is the biggest obstacle you’ve overcome?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What’s the worst job you’ve ever had?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What is something you recently overreacted to?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "Who do you consider to be a mentor, and do they know it?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "If you had a time machine, what time and place would you go to?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What’s an assumption you once had about adult life that turned out to not be true?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "If you could learn to communicate better with one group (humans or otherwise), which would you choose?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What article of clothing do you personally find especially attractive?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What’s something you wish you had said, but didn’t because you were worried about the consequences?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What’s the stupidest purchase you’ve ever made?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  },
  {
    questionText: "What is the most unusual thing you’ve ever eaten?",
    questionType: "easy",
    questionImg: "",
    isMultipleChoice: false,
    isVocalQuestion: true,
    isForcedAnswer: false,
    isShortAnswer: true,
    isDrawingQuestion: false,
    hasBeenAsked: false,
  }
];

export default questions;
